DROP DATABASE IF EXISTS torneos_ligas_ddbb;
CREATE DATABASE torneos_ligas_ddbb;
USE torneos_ligas_ddbb;


CREATE TABLE TIPO_USUARIO
(
	ID_TUSU INT NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR(10)
);

CREATE TABLE TIPO_PRIV
(
	ID_TPRIV INT NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR(10)
);

CREATE TABLE TARJETAS
(
	NUMERO  INT(16) NOT NULL PRIMARY KEY,
    PROPIETARIO VARCHAR(100),
    FECH_CADUCIDAD DATE NOT NULL,
    CVV INT(3) NOT NULL
);

CREATE TABLE TIPO_JUEGO
(
	ID_TJUEGO INT NOT NULL PRIMARY KEY,
    VIDEOJUEGO VARCHAR(40) NOT NULL
);

CREATE TABLE CLUBS
(
	ID_CLUB VARCHAR(10) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50),
    
    ID_TJUEGO INT NOT NULL,
    
    FOREIGN KEY(ID_TJUEGO) REFERENCES TIPO_JUEGO(ID_TJUEGO)
);

CREATE TABLE USUARIOS
(
	NICK VARCHAR(15) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDOS VARCHAR(40) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    FECH_NAC DATE NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CLAVE VARCHAR(50) NOT NULL,
    
    ID_TUSU INT NOT NULL,
    ID_CLUB VARCHAR(10),
    
   FOREIGN KEY(ID_TUSU) REFERENCES  TIPO_USUARIO(ID_TUSU),
   FOREIGN KEY(ID_CLUB) REFERENCES  CLUBS(ID_CLUB)
);


CREATE TABLE TORNEOS
(
	ID_TORNEO VARCHAR(10) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(1000) NOT NULL,
    PLAZAS INT NOT NULL,
    PRECIO DEC(9,2),
    ESTADO VARCHAR(10),
    FECH_INIC DATE NOT NULL,
    FECH_FIN DATE NOT NULL,
    IMG VARCHAR(1000) NOT NULL,
    
    NICK VARCHAR(15) NOT NULL,
    ID_TJUEGO INT NOT NULL,
    
    FOREIGN KEY(NICK) REFERENCES USUARIOS(NICK),
    FOREIGN KEY(ID_TJUEGO) REFERENCES TIPO_JUEGO(ID_TJUEGO)
);

CREATE TABLE LIGAS
(
	ID_LIGA VARCHAR(10) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(1000) NOT NULL,
    ESTADO VARCHAR(10),
    FECH_INIC DATE NOT NULL,
    FECH_FIN DATE NOT NULL,
    
    ID_TJUEGO INT NOT NULL,
    
     FOREIGN KEY(ID_TJUEGO) REFERENCES TIPO_JUEGO(ID_TJUEGO)
);

CREATE TABLE RESERVAS
(
	ID_RESERVA VARCHAR(10) NOT NULL PRIMARY KEY,
    FECH_RESERVA DATE NOT NULL,
    PRECIO DEC(9,2),
    
    NICK VARCHAR(15) NOT NULL,
    ID_TORNEO VARCHAR(10) NOT NULL,
    
    FOREIGN KEY(NICK) REFERENCES USUARIOS(NICK),
    FOREIGN KEY(ID_TORNEO) REFERENCES TORNEOS(ID_TORNEO)
    
);

CREATE TABLE MONEDERO
(
	ID_MONEDERO VARCHAR(40) NOT NULL PRIMARY KEY,
    TOKEN INT NOT NULL,
    
    NICK VARCHAR(15) NOT NULL,
    
    FOREIGN KEY(NICK) REFERENCES USUARIOS(NICK)
);

CREATE TABLE USUARIOS_PRIV
(
	NICK VARCHAR(15) NOT NULL,
    ID_TPRIV INT NOT NULL,
    
    PRIMARY KEY(NICK, ID_TPRIV),
    
    FOREIGN KEY(NICK) REFERENCES USUARIOS(NICK),
    FOREIGN KEY(ID_TPRIV) REFERENCES TIPO_PRIV(ID_TPRIV)
);

CREATE TABLE USUARIOS_TARJETAS
(
	NICK VARCHAR(15) NOT NULL,
    NUMERO INT(16) NOT NULL,
    
    PRIMARY KEY(NICK,NUMERO),
    
    FOREIGN KEY(NICK) REFERENCES USUARIOS(NICK),
    FOREIGN KEY(NUMERO) REFERENCES TARJETAS(NUMERO)
);

CREATE TABLE LIGAS_CLUBS
(
	ID_LIGA VARCHAR(10) NOT NULL,
    ID_CLUB VARCHAR(10) NOT NULL,
    
    PRIMARY KEY(ID_LIGA, ID_CLUB),
    
    FOREIGN KEY(ID_CLUB) REFERENCES  CLUBS(ID_CLUB),
    FOREIGN KEY(ID_LIGA) REFERENCES  LIGAS(ID_LIGA)
);
